# Generated by Django 3.2.7 on 2021-10-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(blank=True, default='よろしくお願いします', max_length=200, null=True, verbose_name='自己紹介'),
        ),
    ]
