# Generated by Django 3.2.7 on 2021-10-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='../static/picture/8074e2c65a3ab65d0ce7b482795b7ac0.jpg', upload_to='icons', verbose_name='アイコン画像'),
        ),
    ]
