# Generated by Django 3.2.7 on 2021-09-08 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(blank=True, max_length=20)),
                ('content', models.CharField(blank=True, max_length=140)),
                ('category', models.CharField(choices=[('kawaii', 'かわいい'), ('cool', 'かっこいい')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
