# Generated by Django 3.2.7 on 2021-09-19 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210910_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=140, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='作品ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/picture/01', upload_to='images', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='relation',
            field=models.ManyToManyField(blank=True, related_name='_post_post_relation_+', to='post.Post', verbose_name='関連'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='post.Tag', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, verbose_name='タイトル'),
        ),
    ]
