# Generated by Django 3.2.7 on 2021-09-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210919_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/icon.png', upload_to='images', verbose_name='画像')),
                ('post_id',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='post.post'))
            ],
        ),
    ]
