# Generated by Django 3.2.7 on 2021-09-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210925_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.images'),
        ),
    ]
