# Generated by Django 3.2.7 on 2021-10-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='admin', max_length=100, verbose_name='作者'),
        ),
    ]
