# Generated by Django 3.2.7 on 2021-10-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='コメント'),
        ),
    ]
