# Generated by Django 3.2.7 on 2021-10-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20211022_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='admin', max_length=100, verbose_name='いいねした人')),
                ('postid', models.UUIDField(verbose_name='作品ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='いいねした時間')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
