# Generated by Django 3.2.7 on 2021-10-28 13:00

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20211023_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/icon.png', upload_to=post.models.image_directory_path, verbose_name='画像'),
        ),
    ]
