# Generated by Django 3.2.7 on 2021-10-29 01:23

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20211023_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flyer',
            field=models.ImageField(default='../static/picture/8074e2c65a3ab65d0ce7b482795b7ac0.jpg', upload_to=post.models.flyers_path, verbose_name='フライヤー'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='../static/picture/8074e2c65a3ab65d0ce7b482795b7ac0.jpg', upload_to=post.models.images_path, verbose_name='画像'),
        ),
    ]
