# Generated by Django 3.2.7 on 2021-10-29 00:46

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='../static/picture/8074e2c65a3ab65d0ce7b482795b7ac0.jpg', upload_to=post.models.image_directory_path, verbose_name='画像'),
        ),
    ]
