# Generated by Django 3.2.9 on 2021-12-04 09:40

from django.db import migrations, models
import post.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_comment_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('author', models.CharField(default='admin', max_length=100, verbose_name='作者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿時間')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='作品ID')),
                ('image', models.ImageField(default='../static/picture/8074e2c65a3ab65d0ce7b482795b7ac0.jpg', upload_to=post.models.images_path, verbose_name='画像')),
                ('like', models.IntegerField(default=0)),
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='親ID')),
            ],
        ),
    ]
