# Generated by Django 3.2.9 on 2021-12-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_exhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='post_id',
            field=models.CharField(default='admin', max_length=10, verbose_name='親ID'),
        ),
    ]
