# Generated by Django 3.2.9 on 2021-12-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_post_is_exhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='post_id',
            field=models.CharField(default='admin', max_length=100, verbose_name='親ID'),
        ),
    ]
