# Generated by Django 3.2.9 on 2021-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=44, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=10, verbose_name='タイトル'),
        ),
    ]
